# Generated by Django 2.2.3 on 2019-07-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossmedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='friend_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
