# Generated by Django 2.2.3 on 2019-07-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossmedia', '0002_auto_20190729_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
