# Generated by Django 2.2.3 on 2019-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossmedia', '0003_remove_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
