# Generated by Django 2.2.3 on 2019-07-29 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crossmedia', '0004_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='friend_id',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
