# Generated by Django 2.2.3 on 2019-07-30 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crossmedia', '0009_auto_20190729_2211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendlist',
            unique_together={('user', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='friendrequestlist',
            unique_together={('user', 'requested_user')},
        ),
    ]
